name: Build docker image
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker_build:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        platform: [ubuntu-latest]  # You can test on macos-latest and windows-latest as well
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Init repo
        run: make init NAME=github.com/ashishb/golang-template-repo
      - name: Fetch modules
        run: touch go.sum && go mod tidy
      - name: Docker build
        run: make docker_build
